language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer selfupdate
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

notifications:
  email: matthiasnoback@gmail.com

cache:
  directories:
    - $HOME/.composer
