name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - main
            - multiple-php-versions-github-actions

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                php:
                    - "7.3"
                    - "7.4"
                    - "8.0"
                    # - "8.1"
                    # - "8.2"
                    # - "8.3"
                dependencies:
                    - "highest"
                    - "lowest"
                actions:
                    -
                        name: "PHPStan"
                        run: vendor/bin/phpstan

                    -
                        name: "PHPUnit"
                        run: vendor/bin/phpunit

        name: ${{ matrix.actions.name }} on PHP ${{ matrix.php }} with ${{ matrix.dependencies }} dependencies
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }})
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v2"
                with:
                    dependency-versions: ${{ matrix.dependencies }}

            -   run: ${{ matrix.actions.run }}
